"use client";
import{useEffect,useRef,useState}from"react";import{useRouter}from"next/navigation";import{submitStageA}from"../actions";
type Draft={decision:string;label:string;definition:string;notes:string};
const choices=[["ACCEPT_SIMPLE","One clear meaning","The entry expresses one reasonably clear meaning."],["ACCEPT_VARIANT","Variant of another form","A spelling, noun-class, or grammatical variant."],["SPLIT_SENSES","Contains multiple meanings","Meanings should be considered separately."],["NEEDS_EXPERT","Needs more linguistic review","Evidence is insufficient. Do not guess."]] as const;
export default function StageAForm({assignmentId,initial}:{assignmentId:string;initial:Draft}){
 const router=useRouter(),[draft,setDraft]=useState(initial),[status,setStatus]=useState<"idle"|"saving"|"saved"|"error">(initial.decision?"saved":"idle"),[savedAt,setSavedAt]=useState<string|null>(null),[submitting,setSubmitting]=useState(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),latest=useRef(draft),version=useRef(0),chain=useRef<Promise<void>>(Promise.resolve()),mounted=useRef(true);
 useEffect(()=>()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current)},[]);
 const enqueue=(value:Draft)=>{const requestVersion=++version.current;setStatus("saving");chain.current=chain.current.then(async()=>{const response=await fetch(`/api/reviewer/drafts/${assignmentId}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...value,version:requestVersion})});const result=await response.json();if(!response.ok)throw new Error(result.message);if(mounted.current&&requestVersion===version.current){setSavedAt(result.savedAt);setStatus("saved")}}).catch(()=>{if(mounted.current&&requestVersion===version.current)setStatus("error")});return chain.current};
 const schedule=(next:Draft)=>{latest.current=next;setDraft(next);if(timer.current)clearTimeout(timer.current);if(next.decision){setStatus("saving");timer.current=setTimeout(()=>enqueue(latest.current),800)}};
 const flush=async()=>{if(timer.current){clearTimeout(timer.current);timer.current=null}if(latest.current.decision)await enqueue(latest.current);await chain.current};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!draft.decision)return;setSubmitting(true);await flush();const data=new FormData();data.set("assignment",assignmentId);data.set("decision",latest.current.decision);data.set("label",latest.current.label);data.set("definition",latest.current.definition);data.set("notes",latest.current.notes);try{await submitStageA(data);router.refresh()}finally{if(mounted.current)setSubmitting(false)}};
 const readable=savedAt?new Date(savedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit",second:"2-digit"}):null;
 return <form onSubmit={submit} className="card"><h2>Your independent linguistic judgment</h2><div className="choices" role="radiogroup" aria-label="Linguistic judgment">{choices.map(choice=><label className="choice" key={choice[0]}><input type="radio" name="decision" value={choice[0]} checked={draft.decision===choice[0]} onChange={()=>schedule({...draft,decision:choice[0]})} required/><strong>{choice[1]}</strong><br/><span className="muted">{choice[2]}</span></label>)}</div><label htmlFor="concept-label">Suggested concept label (optional)</label><input id="concept-label" value={draft.label} onChange={e=>schedule({...draft,label:e.target.value})}/><label htmlFor="preferred-definition">Preferred or clearer definition (optional)</label><textarea id="preferred-definition" value={draft.definition} onChange={e=>schedule({...draft,definition:e.target.value})}/><label htmlFor="reviewer-notes">Reviewer notes (optional)</label><textarea id="reviewer-notes" value={draft.notes} onChange={e=>schedule({...draft,notes:e.target.value})}/><p className={`save-status ${status}`} role="status" aria-live="polite">{status==="saving"?"Saving…":status==="saved"?(readable?`Saved at ${readable}`:"Saved"):status==="error"?"Unable to save. Keep editing or use Save draft.":"Not yet saved"}</p><div className="warning"><strong>Before continuing:</strong> After submission, this judgment is locked. You will then see Tafsiri&apos;s preliminary automated assessment.</div><div className="nav"><button type="button" className="secondary" disabled={!draft.decision||submitting} onClick={()=>flush()}>{status==="saving"?"Saving…":"Save draft"}</button><button disabled={!draft.decision||submitting}>{submitting?"Submitting…":"Submit Linguistic Judgment"}</button></div></form>
}
