import{test,expect}from"@playwright/test";import AxeBuilder from"@axe-core/playwright";import{adminClient,credentials,ids,login}from"./fixtures";
const accessible=async(page:import("@playwright/test").Page)=>{const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(v=>["critical","serious"].includes(v.impact??""))).toEqual([])};
test.describe.serial("local Tafsiri portal",()=>{
 test("anonymous routes and sign-in accessibility",async({page})=>{await page.goto("/reviewer/dashboard");await expect(page).toHaveURL(/auth\/sign-in/);await page.goto("/admin/dashboard");await expect(page).toHaveURL(/auth\/sign-in/);await accessible(page)});
 test("reviewer onboarding persists without self-activation",async({page})=>{await login(page,"a");await page.goto("/reviewer/onboarding");for(let i=0;i<3;i++)await page.getByRole("button",{name:/Save & continue/}).click();await page.getByLabel(/experience with Luwanga/).selectOption("advanced");await page.getByText("No",{exact:true}).click();await page.getByRole("button",{name:/Save & continue/}).click();for(let i=0;i<3;i++)await page.getByRole("button",{name:/Save & continue/}).click();await page.getByLabel(/agree to participate/).check();await page.getByRole("button",{name:/Save & continue/}).click();await page.locator("form").evaluate((form:HTMLFormElement)=>form.requestSubmit());await expect(page.getByText(/awaiting researcher approval/)).toBeVisible();const sb=adminClient(),{data:p}=await sb.from("reviewer_study_participation").select("*").eq("id",ids.participationA).single(),{data:e}=await sb.from("reviewer_dialect_expertise").select("*").eq("reviewer_id",ids.profileA).single();expect(p.participation_status).toBe("onboarding");expect(p.participation_acknowledged_at).toBeTruthy();expect(p.onboarding_completed_at).toBeTruthy();expect(e).toMatchObject({expertise_level:"advanced",self_reported:true,native_speaker:false});await accessible(page)});
 test("admin activation and assignment setup",async({page})=>{await login(page,"admin");await page.goto(`/admin/reviewers/${ids.profileA}`);await expect(page.getByText("Acknowledgment: Recorded")).toBeVisible();await page.getByRole("button",{name:"Activate Reviewer"}).click();await expect(page.getByText("Participation: active")).toBeVisible();const sb=adminClient();await sb.from("review_assignments").insert(ids.items.slice(0,3).map(evaluation_item_id=>({evaluation_item_id,reviewer_id:ids.profileA})));const{data:p}=await sb.from("reviewer_study_participation").select("participation_status").eq("id",ids.participationA).single();expect(p.participation_status).toBe("active");await accessible(page)});
 test("full autosave, blinding, lock, Stage B and next item",async({page})=>{await login(page,"a");await page.goto("/reviewer/dashboard");await page.getByRole("link",{name:"Continue review"}).click();await expect(page.locator("body")).not.toContainText("Preliminary classification");expect(await page.content()).not.toContain("SECRET_PIPELINE_MARKER");await page.getByLabel(/One clear meaning/).check();await page.getByLabel(/Suggested concept label/).fill("Local concept");await expect(page.getByRole("status")).toContainText(/Saved at/,{timeout:20000});await page.reload();await expect(page.getByLabel(/Suggested concept label/)).toHaveValue("Local concept");await page.getByRole("button",{name:"Submit Linguistic Judgment"}).click();await expect(page.getByRole("heading",{name:/original judgment is now locked/})).toBeVisible();await page.getByLabel(/classification reasonable/).selectOption("YES");await page.getByLabel(/correct about ambiguity/).selectOption("YES");await page.getByRole("button",{name:"Submit final review"}).click();await expect(page).toHaveURL(/reviewer\/review\//);const sb=adminClient(),{data:n}=await sb.from("review_annotations").select("annotation_status,primary_decision").eq("assignment_id",(await sb.from("review_assignments").select("id").eq("evaluation_item_id",ids.items[0]).eq("reviewer_id",ids.profileA).single()).data.id).single();expect(n).toMatchObject({annotation_status:"submitted",primary_decision:"ACCEPT_SIMPLE"})});
 test("cross-reviewer and admin isolation",async({page,request})=>{await login(page,"a");const sb=adminClient(),{data:b}=await sb.from("review_assignments").select("id").eq("reviewer_id",ids.profileB).single();await page.goto(`/reviewer/review/${b.id}`);await expect(page.getByText(/This page could not be found/)).toBeVisible();await page.goto("/admin/dashboard");await expect(page).toHaveURL(/pending-access/);const response=await request.post("/api/admin/invitations",{data:{email:"x@test.invalid",reviewerCode:"LUW-R999"}});expect(response.status()).toBeGreaterThanOrEqual(300)});
 test("responsive and keyboard decision controls",async({page})=>{await login(page,"a");for(const width of[375,768,1440]){await page.setViewportSize({width,height:900});await page.goto("/reviewer/dashboard");const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow).toBe(false)}await page.goto("/reviewer/dashboard");await page.getByRole("link",{name:"Continue review"}).focus();await page.keyboard.press("Enter");await page.getByLabel(/One clear meaning/).focus();await page.keyboard.press("Space");await expect(page.getByLabel(/One clear meaning/)).toBeChecked();await accessible(page)});
 test("withdrawal preserves completed evidence and ends access",async({page})=>{await login(page,"admin");await page.goto(`/admin/reviewers/${ids.profileA}`);await page.getByLabel(/understand and confirm/).check();await page.getByRole("button",{name:"Withdraw Reviewer"}).click();await expect(page.getByText(/Participation withdrawn/)).toBeVisible();const sb=adminClient(),{data:p}=await sb.from("reviewer_study_participation").select("participation_status").eq("id",ids.participationA).single(),{data:a}=await sb.from("review_assignments").select("assignment_status").eq("reviewer_id",ids.profileA);expect(p.participation_status).toBe("withdrawn");expect(a.some(x=>x.assignment_status==="completed")).toBe(true);expect(a.some(x=>x.assignment_status==="deactivated")).toBe(true)});
 test("invalid auth callback is friendly",async({page})=>{await page.goto("/auth/callback");await expect(page).toHaveURL(/auth\/sign-in\?error=invalid_callback/);await page.goto("/auth/forgot-password");await accessible(page)});
});
// @ts-nocheck -- Supabase E2E fixture rows are asserted at runtime before use.
