"use client";
import { useActionState, useState } from "react";
import { completeOnboarding, type OnboardingResult } from "./actions";
const steps=["Welcome","About Project Tafsiri","About this study","Language & dialect experience","Participation information","How to review","Practice example","Acknowledgment","Ready for review"];
const initial:OnboardingResult={ok:false,message:""};
export default function OnboardingWizard({initialStep,initialExpertise,initialNative}:{initialStep:number;initialExpertise:string;initialNative:boolean|null}){
 const[i,setI]=useState(initialStep),[expertise,setExpertise]=useState(initialExpertise),[native,setNative]=useState(initialNative===null?"":initialNative?"yes":"no"),[ack,setAck]=useState(false);const[state,action,pending]=useActionState(completeOnboarding,initial);
 if(state.ok)return <main className="shell"><div className="card"><h1>Onboarding complete</h1><p>{state.message}</p></div></main>;
 const next=()=>{if(i===3&&!expertise)return;if(i===7&&!ack)return;setI(Math.min(steps.length-1,i+1))};
 return <main className="shell"><p className="eyebrow">Onboarding · Step {i+1} of {steps.length}</p><div className="progress" aria-label={`Step ${i+1} of ${steps.length}`}><span style={{width:`${(i+1)/steps.length*100}%`}}/></div><form action={action} className="card"><input type="hidden" name="expertise" value={expertise}/><input type="hidden" name="nativeSpeaker" value={native}/><input type="hidden" name="acknowledged" value={ack?"yes":"no"}/><h1>{steps[i]}</h1>
 {i===0&&<p>Project Tafsiri is developing better computational resources for Luhya languages and dialects. You may stop and return later.</p>}{i===1&&<p>Community linguistic knowledge guides this research. Human judgments remain more important than automated suggestions.</p>}{i===2&&<p>Human Evaluation 001 concerns Luwanga dictionary entries. You will independently review only assigned items and should never guess.</p>}{i===3&&<><label htmlFor="expertise">How would you describe your experience with Luwanga?</label><select id="expertise" value={expertise} onChange={e=>setExpertise(e.target.value)} required><option value="" disabled>Select one</option>{["native","fluent","advanced","familiar"].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select><fieldset><legend>Did you acquire Luwanga as a native speaker? (optional)</legend><label><input type="radio" checked={native==="yes"} onChange={()=>setNative("yes")}/> Yes</label><label><input type="radio" checked={native==="no"} onChange={()=>setNative("no")}/> No</label></fieldset><p className="muted">Self-reported. Luwanga experience does not imply experience in another Luhya dialect.</p></>}{i===4&&<><p>You will make independent linguistic judgments. Responses are stored for Project Tafsiri research and represented primarily by reviewer code in research exports.</p><p>You may stop and return. To withdraw, contact [research support]. Never guess an uncertain meaning.</p></>}{i===5&&<p>Choose one clear meaning, variant, multiple meanings, or needs more review. Tafsiri&apos;s assessment remains hidden until your judgment is submitted.</p>}{i===6&&<div className="warning">Practice: if an entry combines unrelated definitions and you cannot separate them confidently, choose “Needs more linguistic review.”</div>}{i===7&&<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I have read participation information version HE001-PARTICIPATION-V1 and agree to participate.</label>}{i===8&&<><p>Your information is ready to save.</p><div className="warning">Completing onboarding does not activate participation. A researcher must review and approve it.</div></>}
 <p role="status">{state.message}</p><div className="nav"><button type="button" className="secondary" disabled={!i||pending} onClick={()=>setI(i-1)}>Previous</button>{i<steps.length-1?<button type="button" disabled={pending||(i===3&&!expertise)||(i===7&&!ack)} onClick={next}>Save &amp; continue</button>:<button disabled={pending}>{pending?"Saving…":"Save & finish"}</button>}</div></form></main>;
}
