import Link from"next/link";import{reviewerContext}from"@/lib/auth";import{createAdminSupabase}from"@/lib/supabase/admin";import{resumeAssignment,type ResumeRow}from"@/lib/review-resume";import{HE001_STUDY_KEY}from"@/lib/study";
export default async function Dashboard(){
 const{sb,profile}=await reviewerContext();if(!profile)return <main className="shell"><div className="card"><h1>Reviewer access pending</h1><p>Your reviewer account has not been activated yet.</p></div></main>;
 const trusted=createAdminSupabase(),{data:study}=await trusted.from("evaluation_studies").select("id,title").eq("study_key",HE001_STUDY_KEY).maybeSingle();
 const{data:p}=study?await trusted.from("reviewer_study_participation").select("participation_status,onboarding_completed_at,participation_acknowledged_at").eq("reviewer_id",profile.id).eq("study_id",study.id).maybeSingle():{data:null};
 if(!p)return <main className="shell"><div className="card">You are not currently enrolled in this study.</div></main>;
 const{data:rows=[]}=await sb.from("review_assignments").select("id,assignment_status,assigned_at,review_annotations(annotation_status)").eq("assignment_role","reviewer").order("assigned_at");const active=(rows??[]).filter(x=>x.assignment_status==="active"),completed=(rows??[]).filter(x=>x.assignment_status==="completed").length,next=resumeAssignment(active as ResumeRow[]);
 let message:React.ReactNode;if(p.participation_status==="withdrawn")message=<div className="card"><h2>Participation ended</h2><p>Your completed research work remains preserved. Contact the research team with questions.</p></div>;else if(p.participation_status==="completed")message=<div className="card"><h2>Study complete</h2><p>Thank you for completing your assigned reviews.</p></div>;else if(!p.onboarding_completed_at)message=<Link className="button" href="/reviewer/onboarding">Continue onboarding</Link>;else if(p.participation_status!=="active")message=<div className="card">Your onboarding is complete and awaiting researcher approval.</div>;else if(!next)message=<div className="card">You do not have review items assigned yet.</div>;else message=<Link className="button" href={`/reviewer/review/${next.id}`}>Continue review</Link>;
 return <main className="shell"><p className="eyebrow">Human Evaluation 001 · Luwanga Semantic Review</p><h1>Welcome, {profile.display_name||profile.reviewer_code}</h1><div className="grid"><div className="card metric"><span>Assigned</span><strong>{rows?.length??0}</strong></div><div className="card metric"><span>Completed</span><strong>{completed}</strong></div><div className="card metric"><span>Remaining</span><strong>{active.length}</strong></div></div>{message}<div className="grid"><Link className="card" href="/reviewer/instructions">Review instructions</Link><Link className="card" href="/reviewer/onboarding">Participation information</Link><Link className="card" href="/reviewer/profile">Account / Security</Link></div></main>
}
